version: '2'
services:
    elasticsearch:
      image: elasticsearch:5
      command: elasticsearch
      environment:
        # This helps ES out with memory usage
        - ES_JAVA_OPTS=-Xmx1g -Xms1g
        - LOGSPOUT=ignore 
      volumes:
        # Persist elasticsearch data to a volume
        - elasticsearch:/usr/share/elasticsearch/data
        # Extra ES configuration options
        - ./es/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - "9200:9200"
        - "9300:9300"

    logstash:
      image: logstash:5
      command: logstash -w 4 -f /etc/logstash/conf.d/logstash.conf
      environment:
        # This helps Logstash out if it gets too busy
        - LS_HEAP_SIZE=2048m
        - LOGSPOUT=ignore 
        - DROP_NON_JSON=false
        - STDOUT=true
      volumes:
        # volume mount the logstash config
        - ./logstash/logstash.conf:/etc/logstash/conf.d/logstash.conf
      ports:
        # GELF port for Docker logs
        - "12201:12201/udp"
        - "5000:5000"
        # UDP port for syslogs
        - "5000:5000/udp"
        # Default TCP port
        - "5001:5001"
      links:
        - elasticsearch

    kibana:
      image: kibana:5
      environment:
        # Point Kibana to the elasticsearch container
        - ELASTICSEARCH_URL=http://elasticsearch:9200
        - LOGSPOUT=ignore 
      ports:
        - "5601:5601"
      links:
        - elasticsearch

    logspout:
      image: gliderlabs/logspout
      environment:
        DEBUG: "true"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: syslog://logstash:5000
      links:
        - logstash

volumes:
  elasticsearch:
